
name: Secure Workflow

on: push  # Trigger when code is pushed

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use API Key
        run: |
          echo "API Key is set"
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Verify Environment Variable
        run: echo "Using secret key in script"
